# Generated by Django 4.1.4 on 2023-01-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreModelo', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=30)),
                ('talles', models.CharField(max_length=30)),
                ('colores', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pijamas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreModelo', models.CharField(max_length=30)),
                ('inviernoverano', models.CharField(max_length=30)),
                ('talles', models.CharField(max_length=30)),
                ('Colores', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RopaInterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreModelo', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=30)),
                ('talles', models.CharField(max_length=30)),
                ('colores', models.CharField(max_length=30)),
            ],
        ),
    ]
